/**
 * PrintLayout — shared A4 layout for all /print/<doc>/[id] routes.
 * Server component (no 'use client') — fetches no data itself, just
 * composes the chrome (header / footer / page setup) around children.
 *
 * The PrintOnMount auto-trigger is rendered at the top so the print
 * dialog fires once the page is ready.
 */

import type { ReactNode } from 'react'
import Link from 'next/link'
import { PrintOnMount } from './print-on-mount'
import { format } from 'date-fns'

export interface Letterhead {
  /** Display name (clinic, hospital, or admin platform). */
  name: string
  /** Tagline / subtitle (specialization, license, etc.). */
  subtitle?: string
  /** Full address. */
  address?: string
  /** Phone, email, website — comma-separated or whatever; rendered as one line. */
  contact?: string
  /** Optional logo URL (rendered as <img>). */
  logoUrl?: string
  /** Optional GST/reg number for invoice templates. */
  gstNo?: string
  /** Optional registration number. */
  registrationNo?: string
}

interface PrintLayoutProps {
  letterhead: Letterhead
  /** Document title shown in the header — e.g. "PRESCRIPTION", "LAB REPORT". */
  title: string
  /** Optional document number — e.g. "RX-2026-0001". Rendered under the title. */
  docNo?: string
  /** Optional ISO date string — printed under the doc no. */
  date?: string | Date
  /** Hide the auto-print button + back button (default false = show). */
  hideControls?: boolean
  children: ReactNode
}

export function PrintLayout({
  letterhead,
  title,
  docNo,
  date,
  hideControls = false,
  children,
}: PrintLayoutProps) {
  return (
    <div className="print-area">
      {!hideControls && <PrintOnMount />}

      {/* Header — clinic/hospital name + contact info */}
      <header className="header" style={{ borderBottom: '2px solid #000' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div style={{ textAlign: 'left' }}>
            {letterhead.logoUrl && (
              <img
                src={letterhead.logoUrl}
                alt={letterhead.name}
                style={{ maxHeight: '50px', marginBottom: '4px' }}
              />
            )}
            <h1 style={{ fontSize: '18px', margin: 0, fontWeight: 700, color: '#0d9488' }}>
              {letterhead.name}
            </h1>
            {letterhead.subtitle && (
              <p style={{ margin: '2px 0', fontSize: '11px', color: '#475569' }}>
                {letterhead.subtitle}
              </p>
            )}
            {letterhead.address && (
              <p style={{ margin: '2px 0', fontSize: '10px', color: '#475569' }}>
                {letterhead.address}
              </p>
            )}
            {letterhead.contact && (
              <p style={{ margin: '2px 0', fontSize: '10px', color: '#475569' }}>
                {letterhead.contact}
              </p>
            )}
          </div>
          <div style={{ textAlign: 'right', minWidth: '180px' }}>
            <p style={{ fontSize: '16px', fontWeight: 700, margin: 0, color: '#000', letterSpacing: '1px' }}>
              {title}
            </p>
            {docNo && (
              <p style={{ fontSize: '11px', margin: '4px 0 0', color: '#475569' }}>
                No: <strong>{docNo}</strong>
              </p>
            )}
            {date && (
              <p style={{ fontSize: '11px', margin: '2px 0 0', color: '#475569' }}>
                Date: <strong>{format(typeof date === 'string' ? new Date(date) : date, 'dd MMM yyyy')}</strong>
              </p>
            )}
          </div>
        </div>
      </header>

      {/* Document content */}
      <main>{children}</main>

      {/* Footer — page info + letterhead GST/reg */}
      <footer className="footer" style={{ borderTop: '1px solid #000', marginTop: '20px', paddingTop: '8px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '9px', color: '#475569' }}>
          <span>
            {letterhead.gstNo && `GST: ${letterhead.gstNo}`}
            {letterhead.gstNo && letterhead.registrationNo && ' | '}
            {letterhead.registrationNo && `Reg: ${letterhead.registrationNo}`}
          </span>
          <span>
            Generated by Doctorooms HMS on {format(new Date(), 'dd MMM yyyy, h:mm a')}
          </span>
        </div>
      </footer>
    </div>
  )
}

/** Small helper for a 2-column info grid (label / value pairs). */
export function InfoGrid({ rows }: { rows: Array<{ label: string; value: string }> }) {
  return (
    <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '12px' }}>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i}>
            <td
              style={{
                width: '20%',
                padding: '3px 8px',
                fontSize: '11px',
                fontWeight: 600,
                color: '#475569',
                border: '1px solid #cbd5e1',
                background: '#f8fafc',
              }}
            >
              {r.label}
            </td>
            <td
              style={{
                padding: '3px 8px',
                fontSize: '11px',
                color: '#000',
                border: '1px solid #cbd5e1',
              }}
            >
              {r.value || '—'}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

/** Section heading inside the print body. */
export function SectionTitle({ children }: { children: ReactNode }) {
  return (
    <h2
      style={{
        fontSize: '12px',
        fontWeight: 700,
        color: '#0d9488',
        margin: '12px 0 6px',
        borderBottom: '1px solid #cbd5e1',
        paddingBottom: '2px',
      }}
    >
      {children}
    </h2>
  )
}

/** Signature block at the bottom — left + right columns. */
export function Signatures({ left, right }: { left?: string; right: string }) {
  return (
    <div className="signature-section" style={{ display: 'flex', justifyContent: 'space-between', marginTop: '40px' }}>
      {left && (
        <div className="signature-line" style={{ borderTop: '1px solid #000', width: '200px', textAlign: 'center', paddingTop: '4px', fontSize: '10px' }}>
          {left}
        </div>
      )}
      <div style={{ width: '200px' }} />
      <div className="signature-line" style={{ borderTop: '1px solid #000', width: '200px', textAlign: 'center', paddingTop: '4px', fontSize: '10px' }}>
        {right}
      </div>
    </div>
  )
}
